### ISSUE TITLE
TornadoVM silently includes (an outdated) commons-math3 that causes problems.

### ISSUE THREAD

**Issue by yazun** [beehive-lab/TornadoVM#151] opened 2021-11-27 14:05 UTC
**Describe the bug**
Some of our unit tests fail when using Tornado VM options due to (surprisingly) included commons-math3 ver 3.2 that is silently added to the classpath.

**How To Reproduce**
Run any code needing commons-math functionality included in a newer commons-math, i.e. the latest 3.6.1: it fails for us trying to resolve `org.apache.commons.math3.fitting.WeightedObservedPoints` class.

The error is misleading by implying there's a problem with modules management while this is a normal resolving conflict.
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module org.apache.commons.math3 not found
```

Provide a **test-case** and **instructions** of how to reproduce the issue.
**Expected behavior**
Commons math of the project should be used, not supplied `tornadovm/bin/sdk/share/java/tornado/commons-math3-3.2.jar`

While resolving
```java
jdk.internal.loader.BuiltinClassLoader::loadClassOrNull
```
should either skip TornadoVM supplied version or should provide an option to put user classpath in front of the the jars supplied with the distribution, commons-math in this case. 

**Computing system setup (please complete the following information):**
 - OS: [e.g. Ubuntu 20] MacOS
 - OpenCL Version 1.2
 - TornadoVM develop 0.13

**Additional context**

**Comment by yazun** [comment] 2021-11-27 14:16
```bash
ls tornadovm/bin/sdk/share/java/tornado/
asm-7.2.jar					hamcrest-core-1.3.jar				lucene-core-8.2.0.jar				tornado-examples-0.13-dev.jar
commons-lang3-3.3.2.jar				jmh-core-1.29.jar				tornado-annotation-0.13-dev.jar			tornado-matrices-0.13-dev.jar
commons-math3-3.2.jar				jopt-simple-4.6.jar				tornado-api-0.13-dev.jar			tornado-runtime-0.13-dev.jar
ejml-core-0.38.jar				jsr305-3.0.2.jar				tornado-benchmarks-0.13-dev.jar			tornado-unittests-0.13-dev.jar
ejml-ddense-0.38.jar				junit-4.13.1.jar				tornado-drivers-common-0.13-dev.jar
ejml-dsparse-0.38.jar				log4j-api-2.13.2.jar				tornado-drivers-opencl-0.13-dev.jar
ejml-simple-0.38.jar				log4j-core-2.13.2.jar				tornado-drivers-opencl-jni-0.13-dev-libs.jar
```

In our case removal of `commons-*` helped. but presence of log4j, junit, asm jars might be problematic as well

**Comment by jjfumero** [comment] 2021-11-30 06:53
Hi @yazun , 
  sorry I don't follow. Which unittests are failing? Are those unittests from the TornadoVM test-suite?

**Comment by yazun** [comment] 2021-11-30 09:35
Hello @jjfumero,
No, our tests when trying to port code to tornadoVM/openCL.

In our case removal of these jars just worked, but maybe appending jars (and not prefixing with them) from `tornadovm/bin/sdk/share/java/tornado/` to a classpath would be a step in good direction, so the project jars are loaded if they exist?

**Comment by jjfumero** [comment] 2021-12-01 06:34
Thanks, we will study this. Can you provide a simple test to reproduce the error?

**Comment by yazun** [comment] 2021-12-01 15:12
The easiest would be to take 3.6.1 code from i.e.
https://github.com/apache/commons-math/tree/3.6.1-release
and run the tests with tornado. Some will likely fail due to --module-path taking precedence over the project classpath.

**Comment by jjfumero** [comment] 2021-12-20 14:54
After we follow the steps with the artifact provided, we are not able to reproduce the problem. We are closing this issue, but if the problem persists, feel free to re-open this issue.

**Comment by yazun** [comment] 2021-12-21 19:43
Added the test in the DPCG test project exposing the issue.

**Comment by jjfumero** [comment] 2021-12-22 05:52
Thank you @yazun . We will take a look

**Comment by jjfumero** [comment] 2022-01-10 11:25
We got the issue. It is now under code review. 
Thanks a lot for the report.

**Comment by jjfumero** [comment] 2022-01-11 10:44
This bug is already fixed in the `develop` branch: https://github.com/beehive-lab/TornadoVM/commit/1b59371371c01d99790d9694f375d93ecf47595d

**Closed by jjfumero** 2022-01-11 10:44 UTC
Labels: bug
