### ISSUE TITLE
Class not found exception after installation on Windows

### ISSUE THREAD

**Issue by andrii0lomakin** [beehive-lab/TornadoVM#472] opened 2024-07-01 08:11 UTC
After installation and execution of stewards.cmd on windows I have got

`python .\bin\tornado
WARNING: Using incubator modules: jdk.incubator.vector
Error: Could not find or load main class None
Caused by: java.lang.ClassNotFoundException: None`

**Comment by stratika** [comment] 2024-07-10 08:06
hi @andrii0lomakin, I guess by `stewards.cmd` you mean `setvars.cmd`? I tried last week (before the release) to install and run TornadoVM on Windows 11. 

Can you please provide some additional information regarding:
- What is the terminal that you are using in Windows? Is it `x64 Native Tools Command Prompt for VS 2022`? 
- What is the command that you built TornadoVM? To understand also which JDK, and backend you are building with.
- Which commit point did you build with?

**Comment by andrii0lomakin** [comment] 2024-07-19 13:25
Hi @stratika 
You can easily reproduce it on a Docker NVIDIA-based image.

**Comment by jjfumero** [comment] 2024-08-12 12:58
TornadoVM does not have any image for PTX + Windows. Since no instructions for reproducing the error are provided, I will close this issue. Feel free to open new issues with concrete steps to reproduce them if this problem persists.

**Closed by jjfumero** 2024-08-12 12:58 UTC

**Comment by andrii0lomakin** [comment] 2024-08-12 13:06
Hi @jjfumero 
I have provided such instructions.
>You can easily reproduce it on a Docker NVIDIA-based image.

Please see above.

**Comment by andrii0lomakin** [comment] 2024-08-12 13:08
```
 docker run --rm -it --entrypoint bash beehivelab/tornadovm-nvidia-openjdk:1.0.6
root@5682c8b3b0cf:/data# tornado
WARNING: Using incubator modules: jdk.incubator.vector
Error: Could not find or load main class None
Caused by: java.lang.ClassNotFoundException: None
root@5682c8b3b0cf:/data#
```

**Comment by jjfumero** [comment] 2024-08-12 13:34
You need to pass your program:

```bash
$ tornado YourJavaProgram
```

You can also try 

```bash
$ tornado --devices
```

Which runs a Java program to explore all devices reachable within your system.  The image you are running is for the OpenCL backend on NVIDIA GPUs. So this image assumes you have an NVIDIA GPU that can run OpenCL.

**Comment by andrii0lomakin** [comment] 2024-08-12 14:42
I supposed that, in such cases, some meaningful message would not harm instead of absence of main class. I mean if I run `java` it prints me usage instructions instead of ClassNotFoundException message.  But it is obviously not critical. Just FYI.

**Comment by jjfumero** [comment] 2024-08-13 08:21
The `ClassNotFoundException` error is thrown by the Java Runtime, not by TornadoVM.

**Comment by andrii0lomakin** [comment] 2024-08-13 09:10
@jjfumero I understand that, but it is possible to change script that it will provide more helpful message in such case. Anyway it is definitely not critical.
