### ISSUE TITLE
Windows Build Failing JNI Library not found

### ISSUE THREAD

**Issue by fkellner** [beehive-lab/TornadoVM#241] opened 2023-04-23 22:00 UTC
I followed the instructions detailed here: https://tornadovm.readthedocs.io/en/latest/installation.html#tornadovm-for-windows-10-11-using-graalvm to the letter.
- I installed GraalVM CE 22.3.1 with Java 17 and Maven
- I installed and updated Msys2 and only used the mingw64 shell 
- I only compiled the opencl backend

When I run `tornado -devices`, I get the following error
```
$ tornado --devices
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Exception in thread "main" java.lang.ExceptionInInitializerError
        at tornado.drivers.opencl@0.15.1-dev/uk.ac.manchester.tornado.drivers.opencl.OCLDriver.<init
>(OCLDriver.java:56)
        at tornado.drivers.opencl@0.15.1-dev/uk.ac.manchester.tornado.drivers.opencl.OCLTornadoDrive
rProvider.createDriver(OCLTornadoDriverProvider.java:50)
        at tornado.runtime@0.15.1-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.loadDriver
s(TornadoCoreRuntime.java:173)
        at tornado.runtime@0.15.1-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.<init>(Tor
nadoCoreRuntime.java:107)
        at tornado.runtime@0.15.1-dev/uk.ac.manchester.tornado.runtime.TornadoCoreRuntime.<clinit>(T
ornadoCoreRuntime.java:83)
        at tornado.drivers.common@0.15.1-dev/uk.ac.manchester.tornado.drivers.TornadoDeviceQuery.mai
n(TornadoDeviceQuery.java:74)
Caused by: uk.ac.manchester.tornado.api.exceptions.TornadoRuntimeException: OpenCL JNI Library not f
ound
        at tornado.drivers.opencl@0.15.1-dev/uk.ac.manchester.tornado.drivers.opencl.OpenCL.<clinit>
(OpenCL.java:68)
        ... 6 more
```

In the folder `<TornadoVM>\dist\tornado-sdk\tornado-sdk-0.15.1-dev-8fe1d4e\lib`, there is a file `tornado-opencl.dll` of size 280KB. 
Is this file simply not found, and if yes, to what should I set the path in the class (https://github.com/beehive-lab/TornadoVM/blob/master/tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OpenCL.java#L49) ?

The instructions state under known errors that issues in Windows may come from a wrong version of GCC or Msys2 (https://tornadovm.readthedocs.io/en/latest/installation.html#known-issues-on-windows). I installed the current version of msys2 (20230318) and `mingw-w64-x86_64-gcc` as instructed and have version 12.2.0. What is the correct version?

I am using a rather old ThinkPad W530 with a NVIDIA Quadro K2000M with Windows 10 (since NVIDIA Drivers won't install on the Ubuntu partition and Intel OpenCL is not available for Linux). But the error does not sound like the graphics drivers are the issue. Any lead would be greatly appreciated! :)

**Comment by jjfumero** [comment] 2023-04-24 07:07
Thank you for the report. The support for Windows 10/11 is still experimental. 
I can't reproduce the error but the documentation is outdated. It needs maven >= 3.9.0.  I am using 3.9.1 and it works for both OpenCL and PTX. I will update the documentation. 

One thing. do you have installed CUDA SDK?, apart from the NVIDIA Driver? Note that you need both, the NVIDIA Driver, which is usually preinstalled on Windows, and the CUDA SDK: https://developer.nvidia.com/cuda-downloads 

Regarding your questions:
> Is this file simply not found, and if yes, to what should I set the path in the class (https://github.com/beehive-lab/TornadoVM/blob/master/tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OpenCL.java#L49) 

This is automatically handled by the `tornado` command. It uses 
`-Djava.library.path=/path/to/TornadoVM/bin/sdk/lib`

> The instructions state under known errors that issues in Windows may come from a wrong version of GCC or Msys2 (https://tornadovm.readthedocs.io/en/latest/installation.html#known-issues-on-windows). I installed the current version of msys2 (20230318) and mingw-w64-x86_64-gcc as instructed and have version 12.2.0. What is the correct version?

The GCC 12.2.0 should be fine. I am also using this one. 

> I am using a rather old ThinkPad W530 with a NVIDIA Quadro K2000M with Windows 10 (since NVIDIA Drivers won't install on the Ubuntu partition and Intel OpenCL is not available for Linux). But the error does not sound like the graphics drivers are the issue. Any lead would be greatly appreciated! :)

Intel OpenCL is available through oneAPI. I have this installed. `oneAPI` gives you access to OpenCL for Intel HD Graphics, Intel CPUs and FPGAs (emulation mode if there is no physical FPGA). 

If it helps, here's my configuration (my `source.sh` file):

```bash
#!/bin/bash

export JAVA_HOME="C:\Users\jjfum\Documents\bin\jvms\graalvm-ce-java17-windows-amd64-22.3.1\graalvm-ce-java17-22.3.1"

## NEXT TWO LINES NECESSARY TO BUILD PTX (NVIDIA CUDA) BACKEND
## COMMENT THEM OUT OR JUST IGNORE IF YOU ARE NOT INTERESTED IN PTX BUILD
## OTHERWISE UPDATE 'CUDA_PATH' WITH ACTUAL VALUE (REMEMBER OF UNIX_STYLE SLASHES AND SPACES!!!)
export CUDA_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6"
export PTX_LDFLAGS=-L\"$CUDA_PATH/lib/x64\"

# LEAVE THE REST OF FILE 'AS IS'
# DON'T ALTER!
export PATH=$PWD/bin/bin:$PATH               ## This directory will be automatically generated during Tornado compilation
export TORNADO_SDK=$PWD/bin/sdk              ## This directory will be automatically generated during Tornado compilation
CMAKE_FILE=$(where cmake | head -n 1)
export CMAKE_ROOT=${CMAKE_FILE%\\*\\*}
```

Note that I am using CUDA 11.6, so you should change it to the version you have installed.

**Comment by jjfumero** [comment] 2023-04-27 18:19
Since the question was answered, I am closing this issue. Feel free to open new ones if you encounter more questions or find more issues.

**Closed by jjfumero** 2023-04-27 18:19 UTC
Labels: question, documentation, installation
