### ISSUE TITLE
There isn't DataTransferMode.LAST_EXECUTION in DataTransferMode

### ISSUE THREAD

**Issue by bitstuffing** [beehive-lab/TornadoVM#237] opened 2023-03-30 13:20 UTC
**Is your feature request related to a problem? Please describe.**
Well, I'm not a GPU developer, but I'm trying to the best efficient code possible. The best way to do that is define several tasks (I think) and TornadoVM should precompile the code to get efficient kernels running on the GPU.

Talking with other developers we came to a conclusion, data should be transfer to host just at the final execution. But I don't see anything in the documentation and in the DataTransferMode just I see an USER_DEFINED, but... how can I implement it just to read data at the final task executed?

Thanks in advance for taking it in consideration. 

**Describe the solution you'd like**

Build a DataTransferMode.LAST_EXECUTION

Sample (just an idea, not a working scenario because it breaks my Intel GPU sadly ):
```
		WorkerGrid workerGrid = new WorkerGrid2D(4, 16763); // Create a 2D Worker
		GridScheduler gridScheduler = new GridScheduler("s0.t0", workerGrid); // Attach the worker to the Grid
		KernelContext context = new KernelContext();

		TaskGraph taskGraph = new TaskGraph("s0");
		    
		for (int i = 0; i < numIterations; i++) {
			taskGraph.transferToDevice(DataTransferMode.FIRST_EXECUTION, matrix1, matrix2_real, matrix2_img);
		    taskGraph.task("t" + i, MainApplication::multiplyReduce, context, matrix1, matrix2_real, matrix2_img, complex_real, complex_imag); //task t#
		    if(i>0) {
		    	//transfer just to the final
				taskGraph.transferToHost(DataTransferMode.USER_DEFINED, complex_real, complex_imag);
		    }
		}

		//there is no .LAST_EXECUTION
		taskGraph.transferToHost(DataTransferMode.LAST_EXECUTION, complex_real, complex_imag);


		ImmutableTaskGraph immutableTaskGraph = taskGraph.snapshot();
		TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph);

		start = System.currentTimeMillis();
		TornadoExecutionResult executionResult = executionPlan
		    .withProfiler(ProfilerMode.CONSOLE)
		    .withGridScheduler(gridScheduler)
		    .execute();

		executionResult.transferToHost(complex_real,complex_imag);
		executionPlan.freeDeviceMemory();
		
        end = System.currentTimeMillis();
        TornadoProfilerResult profiler = executionResult.getProfilerResult();
        profiler.dumpProfiles();
        
        System.out.println("GPU execution done!");
		System.out.println("Finished at: "+((end-start))+" ms.");
```

**Describe alternatives you've considered**
No idea

**Additional context**
It will be great if I can do more with CPU when I should be waiting for the GPU ends, but... I don't have any idea of doing it.

**Comment by jjfumero** [comment] 2023-03-30 13:42
Hi @bitstuffing . I am not sure I understood your questions.

Let me address a few points:
1. TornadoVM does not pre-compile in the Task-Graph. The Task-Graph is just an annotation for the runtime system to identify the data and the code to be offloaded. However, TornadoVM has a pre-compilation which is enabled through the execution plan:

```java
executionPlan.withWarmUp();
```
2. The `DataTransferMode.USER_DEFINED` is used for optimizing output data transfers (e.g., from the GPU to the CPU). As you defined it, it is correct. The `DataTransferMode.USER_DEFINED` requires the developer to explicitly use `executionResult.transferToHost(yourData);`

3. In general, choose the higher set of threads in the first dimension. 
Example:

```java
WorkerGrid workerGrid = new WorkerGrid2D(16763, 4 );  
```

4. The Task-Graph does not transfers anything. It annotates.

```java
//there is no .LAST_EXECUTION
.transferToHost(DataTransferMode.LAST_EXECUTION, complex_real, complex_imag);
```
This is by design. To transfer under demand, use the execution plan. 

5. I do not get why you have the same tasks with the input data in READ-only side the loop.

```java
for (int i = 0; i < numIterations; i++) {
			taskGraph.transferToDevice(DataTransferMode.FIRST_EXECUTION, matrix1, matrix2_real, matrix2_img);
		    taskGraph.task("t" + i, MainApplication::multiplyReduce, context, matrix1, matrix2_real, matrix2_img, complex_real, complex_imag); //task t#
		    if(i>0) {
		    	//transfer just to the final
				taskGraph.transferToHost(DataTransferMode.USER_DEFINED, complex_real, complex_imag);
		    }
		}
```

The idea with the Task-Graph and the execution plan is separate definition from execution. Task-Graphs are used for definition, while execution plans are used for defining how the task-graph will be execution (which scheduling parameters) and perform the actual execution. 

You can create multiple-tasks, but I think, for your example, you can have R/W data and execute the execution plan multiple times:

```java
taskGraph.transferToDevice(DataTransferMode.EVERY_EXECUTION, matrix1, matrix2_real, matrix2_img);
    taskGraph.task("sample", MainApplication::multiplyReduce, context, matrix1, matrix2_real, matrix2_img, complex_real, complex_imag)
    .taskGraph.transferToHost(DataTransferMode.USER_DEFINED, complex_real, complex_imag);

ImmutableTaskGraph immutableTaskGraph = taskGraph.snapshot();
		TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph);

TornadoExecutionResult executionResult = executionPlan
		    .withProfiler(ProfilerMode.CONSOLE)
		    .withGridScheduler(gridScheduler)
		    .execute();

for (int i = 0; i < numIterations; i++) {
    executionPlan.execute();
}

// Get results  
executionPlan.transferToHost(complex_real,complex_imag);
```

Here there are a few examples:

https://github.com/beehive-lab/TornadoVM/blob/master/tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestAPI.java#L45

**Comment by bitstuffing** [comment] 2023-03-30 14:06
Thanks for the quick answer and the .
The code sampled is not final, let me explain me: 

1.  The only thing that I wanted to know was how exactly I'm able to define several tasks (I want to do a matrix multiplication 600 times f.i.), and just I want to put data the first time, work with it in GPU, and bring the processed data to the CPU just to the final step. If I undestand well, the only way to do it is with DataTransferMode.USER_DEFINED chosen. Anyway, it could be interesting if between the available options: 

- public static final int FIRST_EXECUTION = 0;
- public static final int EVERY_EXECUTION = 1;
- public static final int USER_DEFINED = 2;

The programmer could have the LAST_EXECUTION available, to decide define a number of task, execute it, and then return data, because there are penalties in times moving data from GPU to CPU and could be avoid it. I know that always there is possible to define a better strategy by the developer, but it's easier if you have an option like that available.

2. Thanks for the tip, I was reading the link with the examples but I didn't see anything about several tasks, but now with your code: 
```
for (int i = 0; i < numIterations; i++) {
    executionPlan.execute();
}

// Get results  
executionPlan.transferToHost(complex_real,complex_imag);
```
So I suppose with your explanation when you defines a DataTransferMode.USER_DEFINED, you just move data from GPU to CPU if after an `executionPlan.execute()` is called with a `executioniPlant.transferToHost(...)`, but I didn't know that .execute() is not like an .executeAllTasks(), just launch a single task

**Comment by bitstuffing** [comment] 2023-03-30 14:11
Just one note, when you say:
```
// Get results  
executionPlan.transferToHost(complex_real,complex_imag);
```

are you refering to executionResult? because it this case it should be something like this:
```
for (int i = 0; i < numIterations; i++) {
	executionResult = executionPlan.execute();
}

// Get results  
executionResult.transferToHost(complex_real,complex_imag);
```

or am I wrong?

Thanks in advance for your reply.

**Comment by jjfumero** [comment] 2023-03-30 14:13
Just to clarify: the execution plan will execute all tasks associated with a Task-Graph. There is no way to select individual ones. 

We have some examples in which we have multiple-tasks in a Task-Graph:
- Blur Filter example: one task per RGB channel: https://github.com/jjfumero/tornadovm-examples/blob/master/src/main/java/io/github/jjfumero/BlurFilter.java 
- Something more complex - Computer Vision: https://github.com/beehive-lab/kfusion-tornadovm

**Comment by jjfumero** [comment] 2023-03-30 14:14
> Just one note, when you say:
> 
> ```
> // Get results  
> executionPlan.transferToHost(complex_real,complex_imag);
> ```
> 
> are you refering to executionResult? because it this case it should be something like this:
> 
> ```
> for (int i = 0; i < numIterations; i++) {
> 	executionResult = executionPlan.execute();
> }
> 
> // Get results  
> executionResult.transferToHost(complex_real,complex_imag);
> ```
> 
> or am I wrong?
> 
> Thanks in advance for your reply.

Yes, sorry,  I was referring to the `executionResult`

**Comment by jjfumero** [comment] 2023-04-20 07:14
@bitstuffing, I am closing this issue as it seems the questions have been answered. Feel free to reopen it if needed.

**Closed by jjfumero** 2023-04-20 07:14 UTC
Labels: question, API
