### ISSUE TITLE
[bug] Unbox nodes in GraalVM JIT IR causing compilation errors.

### ISSUE THREAD

**Issue by andrii0lomakin** [beehive-lab/TornadoVM#521] opened 2024-08-01 14:16 UTC
The presence of the Unbox nodes in GrallVM IR is causing compilation errors.

There are several examples of such compilation crashes from this discussion https://github.com/beehive-lab/TornadoVM/discussions/515#discussioncomment-10187348 and this one https://github.com/beehive-lab/TornadoVM/issues/516#issuecomment-2262189786 .

**Comment by andrii0lomakin** [comment] 2024-08-01 14:18
Because I am working on the generation of kernels from basic function and passed to them functional interfaces and will have to deal with this issue anyway - https://github.com/beehive-lab/TornadoVM/issues/516- I will fix this bug first if there are no objections.

**Comment by andrii0lomakin** [comment] 2024-08-12 08:17
Hi @jjfumero .
This is a small update from my side: I have fixed the issue that is shown in this test - https://github.com/beehive-lab/TornadoVM/issues/516#issuecomment-2262189786. I tested only on the OpenCL platform. So, I will test on all platforms before committing the changes.

I am going to add a separate test suite to test support of primitive wrappers (obviously unboxing only; no method calls are supported), and it will include the currently failing test https://github.com/beehive-lab/TornadoVM/discussions/515#discussioncomment-10187348 . 

I suppose there will be other tests that need to be fixed.
So, how do you prefer that I submit this fix as a separate PR or provide PR for all fixed tests?

**Comment by jjfumero** [comment] 2024-08-12 08:23
Hi @andrii0lomakin , we prefer separate PRs. You can submit incremental PRs to support more and  more. The important thing is that the PRs can be reproduced with tests, and those tests can run on multiple platforms (OpenCL, PTX and SPIR-V).

**Comment by andrii0lomakin** [comment] 2024-08-12 08:27
@jjfumero When you mean that you prefer incremental PRs did it imply that you use some kind of PR stacking tool or resolve all upcoming changes manually?

**Comment by jjfumero** [comment] 2024-08-12 08:34
I meant. every PR is one fix, in the case you have different types of fixes.

**Comment by jjfumero** [comment] 2024-09-23 08:33
I am closing this issue since the fix was provided and merged in #533

**Closed by jjfumero** 2024-09-23 08:33 UTC
